#!/bin/bash

set -e

# Variables passed to deployment scripts alphabetically sorted
destination=$1
directory=$2
user=$3

# Grunt build
npm install
grunt

# Scp directory to destination
scp -r -i ~/.ssh/id_txssc_rsa $directory/. $user@$destination